# Generated by Django 3.2.8 on 2021-10-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.TimeField(),
        ),
    ]
