# Generated by Django 3.2.8 on 2021-10-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20211021_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_core',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='Core', max_length=20),
        ),
    ]
